[package]
name = "safe-rs"
authors = ["Enrique Ortiz <e@pendrana.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.151"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11.13", features = ["json"] }
serde_json = "1.0.91"
